[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
# Tell hatch where to find the package
packages = ["src/pygekko"]

[tool.hatch.version]  
path = "src/pygekko/__init__.py"

[project]
name = "pygekko"
authors = [
  { name="Thomas Thomsen" },
]
description = "PyGekko: Gekko Timeseries and Modeling Software for Python"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: C#",
    "Operating System :: Microsoft :: Windows",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
dynamic = ["version"]
dependencies = [            
    # dependencies: 'win32' signifies any Windows version, also 64-bit. Then 'AMD64' restricts to 64-bit.
    # dependencies: On Linux/Mac or on 32-bit, pythonnet will not install, and the user will get an ImportError if trying to use PyGekko.
    "pythonnet >=3.0.1, <4.0.0 ; sys_platform == 'win32' and platform_machine == 'AMD64'",
]

[tool.setuptools.package-data]
mypackage = [
    "native/win-x64/*.*",
    "native/win-x86/*.*"
]

[project.urls]
Homepage = "https://t-t.dk/gekko"
Repository = "https://github.com/thomsen67/GekkoTimeseries"

